<?php

/**
 * Generated by .ci/acf-i18n-strings.php from acf-json. Do not edit.
 * Never loaded; it only lets `wp i18n make-pot` extract ACF field strings.
 */

defined('ABSPATH') || exit;

return;

/* translators: ACF field group: Block - Author. */
_x('Add Author', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Add Column', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Add Content', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Add Item', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Block - Banner, Block - Call Out Card, Block - Icon Grid, Block - Accordion, Block - Listing, Block - Dynamically Related Content, Theme Styling Options, Block - Dynamically Related Events. */
_x('Add Row', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Add Social Media', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Block - Tabs. */
_x('Add Tab Item', 'admin field button label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Determines if this accordion item will be open by default on page load. Only one item should have this checked.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Enter a comma separated list of the post IDs you want to exclude from the filters area of the search page. For example: "12,58,4". See the <a target="_blank" href="/app/themes/wicket-wp-theme/custom/wp_terms_cheat_sheet.php">cheat sheet</a> for available post IDs on this site (must be an admin).', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Enter a comma separated list of the post types you want displayed in the filters area of the search page. For example: "news,resources". See the <a target="_blank" href="/app/themes/wicket-wp-theme/custom/wp_terms_cheat_sheet.php#post_types">cheat sheet</a> for available post types on this site (must be an admin).', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Enter a comma separated list of the post types you want to exclude from the filters area of the search page. For example: "post,page". See the <a target="_blank" href="/app/themes/wicket-wp-theme/custom/wp_terms_cheat_sheet.php">cheat sheet</a> for available post types on this site (must be an admin).', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Enter a comma separated list of the taxonomies you want displayed in the filters area of the search page. For example: "category,product_type,nav_menu". See the <a target="_blank" href="/app/themes/wicket-wp-theme/custom/wp_terms_cheat_sheet.php">cheat sheet</a> for available taxonomy slugs on this site (must be an admin).', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Format: X_position Y_position Blur Colour', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Grab the desired FontAwesome icon classes from https://fontawesome.com/icons', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('How many posts you would like to display per page.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('If \'document\' type is set and this field is left empty, the document title will be used here.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('If left blank label will be marked as ‘Download’', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('If left blank label will be marked as ‘View Page’', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('If title is not provided, default title will be "Related [Post_Type]"', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Newsletter section that appears on top of the footer.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Only available in single post pages.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the event categories you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Select the heading level for the accordion titles.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the news types you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the post types you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the posts or pages you would like to exclude from results.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the product categories you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the resource types you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the taxonomies you would like to use as filters on the page.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Select the topics you would like to appear in this listing.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('This allows the body text to \'float\' below the accordion pill.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Use this to add custom fonts from CDN, for example:
&lt;link rel="stylesheet" href="https://use.typekit.net/bot2tyc.css"&gt;', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('You can override the default document / link icon by using this field.', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('e.g. "Montserrat,sans-serif" or "proxima-nova-condensed,sans-serif"', 'admin field instructions', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('AC Localization', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Accordion Items', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Accordion Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Additional Taxonomies -', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Additional Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Additional Taxonomy Filters', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Alerts Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Author. */
_x('Author', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Author. */
_x('Authors', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Back Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Accent Dark', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Accent Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Callout 1', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Callout 2', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Card', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Dark', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Dark Alternate', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Disabled', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Background Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Image Overlay', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Interactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Interactive Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Label 2', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Light Alternate', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Light Neutral', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Background Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background Tag', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Background White', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Banner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Become a Member', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Body Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Tabs. */
_x('Body Content', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Body Text', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Accent', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Alert', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Banner Bottom', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Call Out', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Card', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Dark', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Disabled', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Dynamic Card', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Featured Card', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Footer Divider', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Footer Social', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Footer Top', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Input Default', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Interactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Interactive Large', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Interactive Medium', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Interactive Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Interactive Small', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Large', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Listing Card', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Main Nav Bottom', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Main Nav Top', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Medium', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Small', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Tag', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border Weights', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Border White', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Borders', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings, Block - Banner, Shared - Button Style. */
_x('Button Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Tabs. */
_x('Button/Link Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('CTA Button Label Override', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('CTA Options', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Card. */
_x('CTA Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Tabs. */
_x('Call To Action', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Call to Action', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Card Accent Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Card Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Card Display', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Card Options', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Card: Show Content Type Tags', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Card: Show Excerpt', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Card: Show Featured Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Card: Show Published Date', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Colour', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Colours', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content, Block - Featured Posts, Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Column Count', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Content', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Content Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Contextual Nav', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Copyright', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Create Account', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Custom Colours', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Custom Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Custom/Other Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Default Sort By', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Default font-family name', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Block - Banner, Block - Call Out Card, Block - Contact Card. */
_x('Description', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('Developer Settings', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('Display Breadcrumb', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('Display Publish Date', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('Display Settings', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Document', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Download Button Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Download Button Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Download Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Downloadable File', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Drop Shadow', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Drop Shadows', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Dropdown Mega Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Dropdown Mega Background Highlight', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Dropdown Mega Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Dropdown Mega Heading Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Dropdown Mega Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Elevation 12', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Elevation 4', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Elevation 8', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Block - Contact Card. */
_x('Email', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Embed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Event Categories', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Event Format', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Events Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Card. */
_x('Excerpt', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Exclude From Results', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Excluded Post IDs', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Excluded Post Types', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Facebook Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Font Family', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Font-Awesome Icon Code', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('FontAwesome Icon Class(es)', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Footer', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Columns', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Footer Navigation', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Card. */
_x('Full Height', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('General', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Global Background Colours', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Global Text Colours', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Head Font HTML Code', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Header', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Heading Level', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Helper Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Helper Link Button Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Author. */
_x('Hide Bio', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Hide Block Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Featured Posts, Block - Dynamically Related Content. */
_x('Hide Content Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Post List, Block - Featured Posts, Block - Listing, Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Hide Date', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Date Filter', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Document Attachment', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Document Format Icon', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Hide Event Category', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Hide Event Format/Location', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Post List, Block - Featured Posts, Block - Listing, Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Hide Excerpt', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Post List, Block - Featured Posts, Block - Listing, Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Hide Featured Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Helper Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Hide Price', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Author. */
_x('Hide Profile Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Search', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Hide Start Date Indicator', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Post List. */
_x('Hide Tags', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Hide Type Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Additional Settings. */
_x('Hide on listings', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Hide social links', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Highlight Dark', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Highlight Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Highlight featured post(s)', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Icon', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Drop Shadows', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Grid Icons', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Grid Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Link URL', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Icon Text', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content, Block - Accordion, Block - Sidebar/Contextual Nav. */
_x('Icon Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Block - Banner, Block - Card. */
_x('Image', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Image Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Informational States', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Input Fields Corner Radius Medium', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Input Fields Corner Radius Small', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Instagram Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Interactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Interactive Corner Radius Large', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Interactive Corner Radius Medium', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Interactive Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Intro', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Items', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Label Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Label/Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Layout', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Layout Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Header Settings, Block - Banner, Block - Call Out Card, Block - Card. */
_x('Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Tabs. */
_x('Link & Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Link & Link Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Link Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Link Reversed Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Link Size', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Block - Call Out Card. */
_x('Link Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('LinkedIn Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner, Block - Call Out Card. */
_x('Links', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Login/Logout', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Main Menu Highlight Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Main Navigation', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Make Buttons Same Width', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Maximum Number of Posts', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Member Portal', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Menu', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Miscellaneous', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Mobile Menu: Use Sub-Menu Dropdowns', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Modal Background Overlay', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Contextual Link Level 1', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Contextual Sublink', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Contextual Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Border', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Border Top', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Newsletter Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Newsletter Text Content', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Social Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Social Border Hover', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Social Text', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Social Text Hover', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Sublink', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Text Content', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Text Interactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Footer Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Links Highlight Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Main Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Main Border', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Main Border Interactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Main Highlight', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Main Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Secondary Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Utility Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Utility Background Highlight', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Nav Utility Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('News Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('News Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Newsletter', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Newsletter Page', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Number of featured post(s)', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Open By Default', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Page Options', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('Page Wrapper Class', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Contact Card. */
_x('Phone', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Phone Number', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Search Form. */
_x('Placeholder', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Post Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Block - Dynamically Related Content, Shared - Post Type. */
_x('Post Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Post Type Filters', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Post List, Block - Featured Posts. */
_x('Posts', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Global Search Settings. */
_x('Posts Per Page', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Product Categories', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Products Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Relation', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Remove Drop shadow', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Resource Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Resource Type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Rounded Corners', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Development Settings. */
_x('Save ACF JSON To', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Search Listing Page', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Secondary Nav Cart Enabled', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Secondary Nav Search Enabled', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Section Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Separate Item Body From Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Set Custom View All Link?', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Show Arrow', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Show Button', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Show CTA', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Show Filter Bar', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Show Filter By Published Date', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('Show Search Bar', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Show Tags', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Show View All Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Show breadcrumbs', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Show date', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Show post type', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Show share links', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Site Logo', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Social Links', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Social Media Links', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Social Media Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Social Sharing', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 0', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 025', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 050', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 075', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 100', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 1000', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 150', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 200', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 250', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 300', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 400', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 500', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 600', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Space 800', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Spacing', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Error', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Error Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Info Primary', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Info Primary Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Info Secondary', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Info Secondary Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Success', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Success Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Warning', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('State Warning Light', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('States', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Status Active', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Status Inactive', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Call Out Card, Block - Contact Card, Block - Featured Posts, Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Style', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Card. */
_x('Subtitle', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Tabs. */
_x('Tab Items', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Footer Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Footer Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Header Background', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Header Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Row', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Row Alternate', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Table Row Border', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Tag Corner Radius', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Tag Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('Taxonomies', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy. */
_x('Taxonomy', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Global Search Settings. */
_x('Taxonomy Filters', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Shared - Taxonomy Term, Block - Dynamically Related Events. */
_x('Taxonomy Term', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events, Shared - Taxonomy Terms. */
_x('Taxonomy Terms', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Text', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Accent', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Accent Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Text Alignment', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Button Label', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Button Label Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Content', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Content Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Content Secondary', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Content Secondary Reversed', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Disabled', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Label 1', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Label 2', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Text Tag', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Block - Banner, Block - Call Out Card, Block - Contact Card, Block - Card, Block - Manually Related Content, Block - Featured Posts, Block - Dynamically Related Content, Block - Author, Block - Tabs, Block - Dynamically Related Events. */
_x('Title', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Title Is A Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Title Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Title Text', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Featured Posts. */
_x('Title colour', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Tooltip', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Topic', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Tracking Codes Right After < body >', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Tracking Codes in < head >', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Typography', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('Use Font-Awesome Icon Codes', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('Utility Nav', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('View All Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('X Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('Youtube Link', 'admin field label', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('This will automatically pull in the social media links', 'admin field message', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('This will automatically pull in the social media sharing links', 'admin field message', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('-- Select Menu --', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('-- Select Post Type --', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('-- Select Taxonomy --', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('-- Select Taxonomy Term --', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('1', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('2', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('3', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('4', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('AND', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('Account Center', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Header Settings, Block - Listing. */
_x('Account Centre', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('All', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Alphabetical (a-z)', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Alphabetical (z-a)', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Blog Types', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Blogs', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Brands', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Card. */
_x('Button', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Card', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('Card View', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Sidebar/Contextual Nav. */
_x('Carets', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Blogs', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Case Studies', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Interviews', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> News', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Resources', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Stories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Categories -> Uncategorized', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Centre', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Sidebar/Contextual Nav. */
_x('Chevrons', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Development Settings. */
_x('Child/Active Theme', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Custom Icon (Upload)', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Custom image', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Date (newest-oldest)', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Date (oldest-newest)', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Default Icon', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Disciplines', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('Document', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Donation Forms', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Event Categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Event Categories -> Summer Events', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Event Categories -> Winter Events', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Events', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Featured image', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Column 1', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Column 2', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Column 3', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Column 4', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Column 5', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Footer Menu', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Formats', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Header Settings, Block - Banner, Block - Call Out Card, Block - Accordion, Shared - Button Style. */
_x('Ghost', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Grid view', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Groups', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H1', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H2', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H3', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H4', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H5', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('H6', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Hybrid', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Image', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Jobs', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Left', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Light', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Card, Block - Manually Related Content, Block - Accordion. */
_x('Link', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Manually Related Content. */
_x('List', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion. */
_x('List View', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('List view', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('Main Menu', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Media', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('News', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('News Type', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('News Type -> Economy', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('News Type -> Finance', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('News Type -> Markets', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('No image', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Content, Block - Dynamically Related Events. */
_x('OR', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Featured Posts. */
_x('One Level', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Organizer Categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Organizers', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Pages', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Development Settings. */
_x('Parent Theme', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Accordion, Block - Sidebar/Contextual Nav. */
_x('Plus/Minus', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Posts', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Header Settings, Block - Banner, Block - Call Out Card, Block - Contact Card, Block - Accordion, Shared - Button Style. */
_x('Primary', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Featured Posts. */
_x('Primary + Secondary Level', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Product Categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Product Tags', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Product categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Advertising', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Cards', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Directories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Learning', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Mailing List Services', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Publications', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Product categories -> Uncategorized', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Product shipping classes', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Product tags', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Products', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Resource Type', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Resources', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Banner. */
_x('Reversed', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Role Based Pricing Rules', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings, Header Settings, Block - Banner, Block - Call Out Card, Block - Contact Card, Block - Accordion, Shared - Button Style. */
_x('Secondary', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Series', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Tags', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Content', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Featured', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Fun', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Happiness', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Important', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Must read', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Tags -> Topic', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Taxonomy. */
_x('Topics', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Shared - Taxonomy Term, Shared - Taxonomy Terms. */
_x('Topics -> Must Read', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Venue Categories', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing. */
_x('Venues', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Dynamically Related Events. */
_x('Virtual', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Listing, Shared - Post Type. */
_x('Woo Product Tabs', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('lg', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('md', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Footer Settings. */
_x('sm', 'admin field option', 'wicket-theme');

/* translators: ACF field group: Block - Icon Grid. */
_x('E.g. "fa-solid fa-circle"', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('E.g. 12,58,4', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('E.g. <!-- Google Tag Manager (noscript) -->   <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PBZBHM"   height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>   <!-- End Google Tag Manager (noscript) -->', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Header Settings. */
_x('E.g. <!-- Google Tag Manager --> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\': new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src= \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f); })(window,document,\'script\',\'dataLayer\',\'GTM-PBZBHM\');</script> <!-- End Google Tag Manager -->', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('E.g. category,product_type,nav_menu', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Global Settings. */
_x('E.g. fa-brands fa-youtube', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('E.g. news,resources', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Global Search Settings. */
_x('E.g. post,page', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Standard Page Settings. */
_x('e.g. homepage-template', 'admin field placeholder', 'wicket-theme');

/* translators: ACF field group: Theme Styling Options. */
_x('px', 'admin field prepend', 'wicket-theme');
