#!/usr/bin/env php
<?php

/**
 * Writes languages/acf-strings.php from acf-json/*.json.
 *
 * `wp i18n make-pot` cannot read ACF JSON, so this lists every translatable
 * field string as an _x() call the .pot hook can extract. Run `composer i18n:acf`
 * after changing ACF field groups, then commit both files.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$textSettings = ['label', 'instructions', 'placeholder', 'prepend', 'append', 'message', 'button_label', 'ui_on_text', 'ui_off_text'];

/** @var array<string, array<string, array<string, true>>> $strings context => string => group titles */
$strings = [];

$collect = function (array $fields, string $group) use (&$collect, &$strings, $textSettings): void {
    foreach ($fields as $field) {
        foreach ($textSettings as $setting) {
            $value = $field[$setting] ?? '';
            if (is_string($value) && trim($value) !== '') {
                $strings['admin field ' . str_replace('_', ' ', $setting)][$value][$group] = true;
            }
        }
        foreach ((array) ($field['choices'] ?? []) as $label) {
            if (is_string($label) && trim($label) !== '') {
                $strings['admin field option'][$label][$group] = true;
            }
        }
        $collect($field['sub_fields'] ?? [], $group);
        foreach ($field['layouts'] ?? [] as $layout) {
            $collect($layout['sub_fields'] ?? [], $group);
        }
    }
};

$files = glob($root . '/acf-json/*.json') ?: [];
sort($files);
foreach ($files as $file) {
    $data = json_decode((string) file_get_contents($file), true);
    if (!is_array($data)) {
        fwrite(STDERR, 'Skipping invalid JSON: ' . basename($file) . PHP_EOL);
        continue;
    }
    $collect($data['fields'] ?? [], (string) ($data['title'] ?? basename($file, '.json')));
}

ksort($strings, SORT_STRING);

$out = "<?php\n\n"
    . "/**\n"
    . " * Generated by .ci/acf-i18n-strings.php from acf-json. Do not edit.\n"
    . " * Never loaded; it only lets `wp i18n make-pot` extract ACF field strings.\n"
    . " */\n\n"
    . "defined('ABSPATH') || exit;\n\n"
    . "return;\n";

$count = 0;
foreach ($strings as $context => $entries) {
    ksort($entries, SORT_STRING);
    foreach ($entries as $string => $groups) {
        $comment = str_replace('*/', '* /', 'ACF field group: ' . implode(', ', array_keys($groups)));
        $out .= "\n/* translators: " . $comment . ". */\n";
        $out .= "_x(" . var_export((string) $string, true) . ', ' . var_export($context, true) . ", 'wicket-theme');\n";
        $count++;
    }
}

file_put_contents($root . '/languages/acf-strings.php', $out);
echo 'Wrote ' . $count . ' strings to languages/acf-strings.php' . PHP_EOL;
